### ISSUE TITLE
rxjs-finnish highlights functions

### ISSUE THREAD

**Issue by gradzio** [cartant/rxjs-tslint-rules#89] opened 2019-04-04 10:20 UTC
When using details config it will error in linter for functions. E.g.:
{
      "functions": false,
      "methods": false,
      "parameters": false,
      "properties": false,
      "variables": false
    }
or 
{
      "functions": false,
      "methods": false,
      "parameters": false,
      "properties": false,
      "variables": true
    }

will highlight functions and methods that return observable.

**Comment by cartant** [comment] 2019-04-04 10:51
It would not be possible for me to reproduce your problem without making a bunch of assumptions, as you have included only a partial configuration an not code snippet.

To see a working configuration, see the examples [within the tests for that rule](https://github.com/cartant/rxjs-tslint-rules/tree/master/test/v6/fixtures/finnish).

**Comment by cartant** [comment] 2019-04-16 12:49
Closing as unactionable due to insufficient information.

**Closed by cartant** 2019-04-16 12:49 UTC
Labels: more information needed
